name: Story
description: User story with testable acceptance criteria. Map to a WU and gate.
title: "STORY: <short name>"
labels: []
body:
  - type: dropdown
    id: persona
    attributes:
      label: Persona
      options:
        - dev
        - qa
        - sre
        - em
    validations:
      required: true
  - type: dropdown
    id: gate
    attributes:
      label: Gate
      options:
        - A
        - B
        - C
        - D
    validations:
      required: true
  - type: dropdown
    id: module
    attributes:
      label: Module
      options:
        - ingest
        - scoring
        - ui
        - bot
        - docs
    validations:
      required: true
  - type: input
    id: wu
    attributes:
      label: Work Unit (WU-ID)
      placeholder: e.g., WU-203
  - type: textarea
    id: story
    attributes:
      label: Story
      description: As a <persona>, I want to <do X>, so that <benefit>.
      placeholder: As a QA, I want flaky tests auto-commented on my PR, so I can act before merge.
    validations:
      required: true
  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria
      description: Bullet list of testable AC. Include budgets if relevant.
      placeholder: |
        - Given a PR with commit SHA X and a flaky test F≥60, the bot posts/updates a single comment.
        - Label 'flaky-tests' is applied only if candidates exist.
        - Comment update is idempotent and rate limited (≤10 writes/min/repo).
    validations:
      required: true
  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      options:
        - label: Tests updated/added
        - label: Docs updated (README/ADR)
        - label: Budgets enforced (a11y/perf/security/privacy)
        - label: Labels applied (gate:*, module:*, persona:*, priority:*)
        - label: WU completed (commit + Build Log + Session State)
  - type: textarea
    id: notes
    attributes:
      label: Notes / Links
      placeholder: Links to designs, PRs, ADRs, or related issues.