name: Test Workflow

on:
  pull_request:
    paths:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"